cameras:
- detection:
    limits:
    - - 54
      - 117
      - 33
    - - 88
      - 222
      - 196
    max_area: 100000
    min_area: 500
  detection_stream_enabled: false
  exposure: 87
  mask_stream_enabled: false
  name: big-color
