cameras:
- detection:
    limits:
    - - 54
      - 117
      - 33
    - - 88
      - 222
      - 196
    max_area: 100000
    min_area: 500
  detection_stream_enabled: true
  exposure: 1000
  mask_stream_enabled: true
  name: usb-CN089W678LG004CMF62AA01_Integrated_Webcam_FHD-video-index0
- detection:
    limits:
    - - 54
      - 117
      - 33
    - - 88
      - 222
      - 196
    max_area: 100000
    min_area: 500
  detection_stream_enabled: true
  exposure: 90
  mask_stream_enabled: true
  name: usb-CN089W678LG004CMF62AA01_Integrated_Webcam_FHD-video-index1
